import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";
import SocialsFooter from "@/components/SocialsFooter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="bg-[url('/map-background.svg')] lg:bg-top-large  sm:bg-top-mid bg-top-small   bg-contain bg-no-repeat "
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-[90vw] max-w-[1440px] pt-10`}
      >
        <header className="w-full">
          <Navbar />
        </header>
        {children}
        <footer>
          <SocialsFooter />
        </footer>
      </body>
    </html>
  );
}
