import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SocialsFooter from "@/components/SocialsFooter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased smCustom755:w-[90vw] w-[100vw] max-w-[1440px] relative flex flex-col justify-center items-center h-fit`}
      >
        <div className="bg-[url('/map-background.svg')] lg:bg-top-large  sm:bg-top-mid bg-top-small   bg-contain bg-no-repeat w-[90%] h-[1000px] -z-50 absolute " />
        <header className="w-full">
          <Navbar />
        </header>
        {children}

        <footer className="w-full px-4">
          <SocialsFooter />
        </footer>
      </body>
    </html>
  );
}
